version: "3.9"

services:
  airflow-init:
    image: apache/airflow:2.9.0
    container_name: airflow_air_init
    entrypoint: ["/bin/bash", "/opt/airflow/init_airflow.sh"]
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
      - ./init_airflow.sh:/opt/airflow/init_airflow.sh
    restart: on-failure

  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: airflow_air_web
    depends_on:
      - airflow-init
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    command: ["bash", "-c", "pip install -r /requirements.txt && airflow webserver"]
    restart: always

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow_air_scheduler
    depends_on:
      - airflow-init
    env_file:
      - .env
    volumes:
      - ./dags:/opt/airflow/dags
      - ./requirements.txt:/requirements.txt
    command: ["bash", "-c", "pip install -r /requirements.txt && airflow scheduler"]
    restart: always
