apiVersion: 1
datasources:
  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    user: grafana
    secureJsonData:
      password: grafana
    jsonData:
      database: metrics
      sslmode: "disable"
      timescaledb: true

